# Generated by Django 5.2.15 on 2026-06-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Unique identifier linking back to the legacy order.', max_length=50, unique=True)),
                ('customer_email', models.EmailField(help_text='Customer email address.', max_length=254)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total order price.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='LegacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Unique identifier from the legacy system.', max_length=50, unique=True)),
                ('raw_data', models.JSONField(help_text='Denormalized order data in JSON format.')),
                ('migrated', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been migrated to the new schema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legacy Order',
                'verbose_name_plural': 'Legacy Orders',
                'ordering': ['external_id'],
                'indexes': [models.Index(fields=['migrated', 'external_id'], name='idx_legacy_migrated_extid')],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit identifier.', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units ordered.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit.', max_digits=10)),
                ('order', models.ForeignKey(help_text='Parent order for this line item.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
            },
        ),
    ]
