# Generated by Django 5.2.15 on 2026-06-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderline',
            table='orders_order_line',
        ),
    ]
